
services:
  ###########################################################################
  # postgres database
  ###########################################################################
  postgres:
    image: postgres:17-alpine
    hostname: postgres
    container_name: postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./infra/init-data.sh:/docker-entrypoint-initdb.d/init-data.sh:Z
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_NON_ROOT_USER
      - POSTGRES_NON_ROOT_PASSWORD
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  ###########################################################################
  # n8n is an extendable workflow automation tool.
  # documentation: https://n8n.io
  ###########################################################################
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: always
    links:
      - postgres
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
      - NODE_ENV=production
      - N8N_PORT=443
      - N8N_PROTOCOL=https
      - N8N_HOST=n8n.${COMPOSE_PROJECT_NAME}.orb.local
      - WEBHOOK_URL=https://n8n.${COMPOSE_PROJECT_NAME}.orb.local
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
    volumes:
      - n8n-data:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy


###########################################################################
# volumes
###########################################################################
volumes:
  pg_data: {}
  n8n-data: {}