
services:
  ###########################################################################
  # postgres database
  ###########################################################################
  postgres:
    image: postgres:17-alpine
    hostname: postgres
    container_name: postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./config/db/init-data.sh:/docker-entrypoint-initdb.d/init-data.sh:Z
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_NON_ROOT_USER
      - POSTGRES_NON_ROOT_PASSWORD
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  ###########################################################################
  # n8n is an extendable workflow automation tool.
  # Documentation: https://n8n.io
  # Environment variables: https://docs.n8n.io/hosting/configuration/environment-variables/
  ###########################################################################
  n8n:
    image: docker.n8n.io/n8nio/n8n
    hostname: n8n
    container_name: n8n
    restart: unless-stopped
    links:
      - postgres
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
      - NODE_ENV=production
      - N8N_EDITOR_BASE_URL=https://n8n.${COMPOSE_PROJECT_NAME}.orb.local
      - WEBHOOK_URL=https://n8n.${COMPOSE_PROJECT_NAME}.orb.local
      - GENERIC_TIMEZONE
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_PERSONALIZATION_ENABLED=false
      - N8N_ENCRYPTION_KEY
      - N8N_USER_MANAGEMENT_JWT_SECRET
      - OLLAMA_HOST=host.docker.internal:11434
      # - N8N_EMAIL_MODE=smtp
      # - N8N_SMTP_HOST=<smtp.sendgrid.net>
      # - N8N_SMTP_PORT=<465>
      # - N8N_SMTP_USER=<apikey>
      # - N8N_SMTP_PASS=<sendgrid api key>
      # - N8N_SMTP_SENDER=<n8n@example.com>
      # - N8N_SMTP_SSL=true
    volumes:
      - n8n_data:/home/node/.n8n
      - ./config/workflows:/workflows
    depends_on:
      postgres:
        condition: service_healthy


###########################################################################
# volumes
###########################################################################
volumes:
  pg_data: {}
  n8n_data: {}